server:
  port: 9001
spring:
  application:
    name: zzadp-eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
    register-with-eureka: false
    fetch-registry: true